from util import const
const.SERVER_IP = "192.168.1.102"
const.SERVER_PORT = 9000
const.TCP_RECEIVE_SIZE = 2048
const.TCP_SEND_SIZE = 2048

const.UPLOAD_SCREEN_SHOT_FINISH = "UPLOAD_SCREEN_SHOT_FINISH"
const.UPLOAD_SCREEN_SHOT = "UPLOAD_SCREEN_SHOT"